## Input Data Schema

# feature id: feature name
# The order must be consistent with the raw data.
# First field is the label. Case insensitive here.

1: if_clicked
2: site_id
3: device_type
4: device_brand
5: device_model
6: os_name
7: os_tp
8: os_version
9: network_type
10: browser_name
11: browser_version
12: country
13: language_flag
14: page_name
15: category_id
16: month
17: weekday
18: day
19: timestamp
20: goods_id
21: new_cate_1_id
22: new_cate_2_id
23: new_cate_3_id
24: new_cate_4_id
25: sku_cate_id
26: trmnl_list_ctr_1
27: trmnl_list_ctr_7
28: trmnl_list_addbag_1
29: trmnl_list_addbag_7
30: trmnl_list_payrate_1
31: trmnl_list_payrate_7
32: trmnl_list_cvr_1
33: trmnl_list_cvr_7
34: trmnl_list_auv_1
35: trmnl_list_auv_7
36: ten_trmnl_list_cvr_1
37: ten_trmnl_list_cvr_7
38: ten_trmnl_list_auv_1
39: ten_trmnl_list_auv_7
40: country_list_ctr_1
41: country_list_ctr_7
42: country_list_addbag_1
43: country_list_addbag_7
44: country_list_payrate_1
45: country_list_payrate_7
46: country_list_cvr_1
47: country_list_cvr_7
48: country_list_auv_1
49: country_list_auv_7
50: ten_country_list_cvr_1
51: ten_country_list_cvr_7
52: ten_country_list_auv_1
53: ten_country_list_auv_7
54: short_flag
55: special_flag
56: model_flag
57: shein_flag
58: staged_flag
59: avg_rating
60: img_commet_rate
61: size_commet_rate
62: last_comet
63: total_comet_num
64: fitwell_rate
65: big_rate
66: small_rate
67: dwell_time
68: ismiss_rate
69: trmnl_sale_rate
70: country_sale_rate
71: ten_trmnl_sale_rate
72: ten_country_sale_rate
73: hotness
74: high_quality_label
75: score
76: detail_page_price
77: sale2to8_cnt
78: c7d_pay_user_cnt
79: c30d_pay_user_cnt
80: return7_rate
81: member_id
82: cookie_id
83: device_id
84: user_id
85: old_customer_flag
86: nation_label
87: country_id
88: subdivisions_id
89: city_id
90: forecast_gender
91: age_range_predict
92: pay_maturity
93: act_lvl
94: new_act_lvl
95: no_pay_days
96: visit_minutes_7d
97: visit_minutes_30d
98: pay_cnt_7d
99: pay_cnt_30d
100: history_cate
101: goodsid_clicked
102: goodsid_carted
103: goodsid_collected
104: goodsid_buyed
105: prefer_style_id
106: prefer_color_id
107: attr_1_value_nm
108: attr_4_value_nm
109: attr_5_value_nm
110: attr_6_value_nm
